const fs = require('fs');

const newRestaurants = `export const restaurants: Restaurant[] = [
  {
    id: "abba-restaurant",
    name: "Abba Restaurant and Everest German Bakery",
    category: "finedining",
    description: "Famous for its bakery items, pizzas, and multi-cuisine menu right on the cliff.",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
    priceRange: "300-800",
    rating: 4.5,
    reviews: 1850,
    popularDishes: ["Apple Pie", "Wood-fired Pizza", "Lasagna", "German Bakery Items"],
    location: { lat: 8.7360, lng: 76.7160 },
    address: "North Cliff, Varkala",
    tags: ["Bakery", "Sea View", "Pizza", "Multi-cuisine"],
    crowdLevel: "high",
    openHours: "8:00 AM – 11:00 PM",
  },
  {
    id: "blue-water",
    name: "Blue Water Restaurant",
    category: "seafood",
    description: "Quiet dining experience overlooking the ocean, away from the bustling north cliff.",
    image: "https://images.unsplash.com/photo-1599058917215-fa77e31fdb4d?w=800&q=80",
    priceRange: "400-1000",
    rating: 4.4,
    reviews: 820,
    popularDishes: ["Kerala Fish Curry", "Prawn Roast", "Fresh Catch", "Cocktails"],
    location: { lat: 8.7240, lng: 76.7090 },
    address: "Odayam Beach, Varkala",
    tags: ["Quiet", "Sea View", "Seafood", "Romantic"],
    crowdLevel: "low",
    openHours: "7:30 AM – 10:30 PM",
  },
  {
    id: "cafe-del-mar",
    name: "Café del Mar",
    category: "finedining",
    description: "Fine dining with Mediterranean and Indian fusion cuisine – perfect for a romantic clifftop dinner.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    priceRange: "1500+",
    rating: 4.8,
    reviews: 445,
    popularDishes: ["Lobster Thermidor", "Kerala Sea Bass", "Truffle Risotto", "Mango Panna Cotta"],
    location: { lat: 8.7375, lng: 76.7162 },
    address: "North Cliff, Varkala",
    tags: ["Fine Dining", "Romantic", "Fusion", "Couple Friendly"],
    crowdLevel: "low",
    openHours: "6:00 PM – 11:00 PM",
  },
  {
    id: "clafouti",
    name: "Clafouti Restaurant",
    category: "seafood",
    description: "One of Varkala's most popular seaside dining spots offering incredible ocean views.",
    image: "https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800&q=80",
    priceRange: "300-900",
    rating: 4.5,
    reviews: 2300,
    popularDishes: ["Tandoori Fish", "Naan", "Prawn Masala", "Continental Breakfast"],
    location: { lat: 8.7350, lng: 76.7160 },
    address: "North Cliff, Varkala",
    tags: ["Popular", "Sea View", "Seafood", "Tandoori"],
    crowdLevel: "high",
    openHours: "7:00 AM – 11:00 PM",
  },
  {
    id: "coffee-temple",
    name: "Coffee Temple",
    category: "cafe",
    description: "The beloved clifftop cafe with panoramic sea views, great coffee, and a legendary breakfast.",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    priceRange: "300-700",
    rating: 4.7,
    reviews: 2100,
    popularDishes: ["Banana Pancakes", "Shakshuka", "Filter Coffee", "Açaí Bowl"],
    location: { lat: 8.7375, lng: 76.7162 },
    address: "North Cliff, Varkala",
    tags: ["Sea View", "Breakfast", "Coffee", "Backpacker Favorite"],
    crowdLevel: "high",
    openHours: "7:00 AM – 10:00 PM",
  },
  {
    id: "darjeeling-cafe",
    name: "Darjeeling Cafe",
    category: "cafe",
    description: "Bohemian vibes, ambient lighting, excellent music, and great global cuisine.",
    image: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80",
    priceRange: "400-800",
    rating: 4.6,
    reviews: 1750,
    popularDishes: ["Momos", "Thukpa", "Pasta", "Cocktails"],
    location: { lat: 8.7380, lng: 76.7165 },
    address: "North Cliff, Varkala",
    tags: ["Bohemian", "Music", "Momos", "Chill Vibe"],
    crowdLevel: "high",
    openHours: "8:00 AM – 11:30 PM",
  },
  {
    id: "gods-own",
    name: "God's Own Country Kitchen",
    category: "kerala",
    description: "A staple for authentic Kerala cuisine served on banana leaves with a sea breeze.",
    image: "https://images.unsplash.com/photo-1589301760014-d929f39ce9b0?w=800&q=80",
    priceRange: "200-600",
    rating: 4.5,
    reviews: 1400,
    popularDishes: ["Kerala Sadya", "Beef Fry", "Meen Pollichathu", "Appam"],
    location: { lat: 8.7370, lng: 76.7163 },
    address: "North Cliff, Varkala",
    tags: ["Authentic", "Kerala Food", "Banana Leaf", "Spicy"],
    crowdLevel: "medium",
    openHours: "11:00 AM – 10:30 PM",
  },
  {
    id: "inda-cafe",
    name: "InDa Cafe",
    category: "cafe",
    description: "Tucked slightly away from the cliff, offering beautiful aesthetic interiors and excellent coffee.",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80",
    priceRange: "200-600",
    rating: 4.8,
    reviews: 950,
    popularDishes: ["Avocado Toast", "Cold Brew", "Smoothie Bowls", "Vegan Pizza"],
    location: { lat: 8.7390, lng: 76.7170 },
    address: "Kurakkanni, Varkala",
    tags: ["Aesthetic", "Vegan Friendly", "Coffee", "Quiet"],
    crowdLevel: "medium",
    openHours: "8:30 AM – 10:00 PM",
  },
  {
    id: "juice-shack",
    name: "The Juice Shack",
    category: "cafe",
    description: "Fresh tropical juices, smoothie bowls, and healthy snacks with a chilled-out vibe.",
    image: "https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=800&q=80",
    priceRange: "100-300",
    rating: 4.6,
    reviews: 1456,
    popularDishes: ["Watermelon Juice", "Mango Smoothie Bowl", "Avocado Toast", "Fresh Coconut"],
    location: { lat: 8.7375, lng: 76.7162 },
    address: "Cliff Road, Varkala",
    tags: ["Healthy", "Budget Friendly", "Juices", "Vegan"],
    crowdLevel: "medium",
    openHours: "8:00 AM – 8:00 PM",
  },
  {
    id: "puccini-tomaso",
    name: "Puccini Tomaso",
    category: "finedining",
    description: "The best authentic Italian pizzas and pastas in Varkala, featuring a real wood-fired oven.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80",
    priceRange: "500-1200",
    rating: 4.7,
    reviews: 890,
    popularDishes: ["Margherita Pizza", "Ravioli", "Tiramisu", "Garlic Bread"],
    location: { lat: 8.7385, lng: 76.7165 },
    address: "North Cliff, Varkala",
    tags: ["Italian", "Pizza", "Wood Fired", "Pasta"],
    crowdLevel: "medium",
    openHours: "12:00 PM – 11:00 PM",
  },
  {
    id: "sea-rock-cafe",
    name: "Sea Rock Beach Restaurant",
    category: "seafood",
    description: "Fresh catch-of-the-day seafood grilled to perfection, right at the cliff edge.",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80",
    priceRange: "700-1500",
    rating: 4.5,
    reviews: 987,
    popularDishes: ["Grilled Tiger Prawns", "Fish Moilee", "Calamari", "Kerala Fish Curry"],
    location: { lat: 8.7375, lng: 76.7162 },
    address: "South Cliff, Varkala",
    tags: ["Seafood", "Sea View", "Grilled", "Fresh Catch"],
    crowdLevel: "high",
    openHours: "12:00 PM – 11:00 PM",
  },
  {
    id: "sreepadmam",
    name: "Sreepadmam Restaurant",
    category: "kerala",
    description: "Authentic Kerala cuisine served on banana leaves – the best local meals at budget prices.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&q=80",
    priceRange: "100-300",
    rating: 4.4,
    reviews: 756,
    popularDishes: ["Kerala Sadya (Feast)", "Fish Curry Rice", "Appam & Stew", "Payasam"],
    location: { lat: 8.7375, lng: 76.7162 },
    address: "Temple Junction, Varkala",
    tags: ["Authentic Kerala", "Budget", "Banana Leaf", "Local Favorite"],
    crowdLevel: "high",
    openHours: "7:00 AM – 9:00 PM",
  },
  {
    id: "sunset-restaurant",
    name: "Sunset Restaurant",
    category: "seafood",
    description: "Incredible views of the sun dipping into the Arabian sea, paired with excellent tandoori.",
    image: "https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=800&q=80",
    priceRange: "400-900",
    rating: 4.3,
    reviews: 1100,
    popularDishes: ["Tandoori Chicken", "Garlic Naan", "Tiger Prawns", "Mojito"],
    location: { lat: 8.7340, lng: 76.7160 },
    address: "North Cliff, Varkala",
    tags: ["Sunset View", "Tandoori", "Cocktails", "Seafood"],
    crowdLevel: "high",
    openHours: "8:00 AM – 11:00 PM",
  },
  {
    id: "trattorias",
    name: "Trattorias",
    category: "finedining",
    description: "A beautiful multi-cuisine restaurant known for large portions and friendly service.",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    priceRange: "300-800",
    rating: 4.4,
    reviews: 1340,
    popularDishes: ["Sizzlers", "Pasta", "Kerala Meals", "Fruit Juices"],
    location: { lat: 8.7378, lng: 76.7160 },
    address: "North Cliff, Varkala",
    tags: ["Multi-cuisine", "Sea View", "Sizzlers"],
    crowdLevel: "medium",
    openHours: "8:00 AM – 11:00 PM",
  },
  {
    id: "white-rabbit",
    name: "White Rabbit Vegetarian Cafe",
    category: "cafe",
    description: "A colorful, vibrant cafe exclusively serving organic, vegetarian, and vegan food.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
    priceRange: "200-500",
    rating: 4.7,
    reviews: 650,
    popularDishes: ["Vegan Burger", "Falafel Wrap", "Kombucha", "Gluten-Free Brownie"],
    location: { lat: 8.7390, lng: 76.7168 },
    address: "Kurakkanni Road, Varkala",
    tags: ["Vegan", "Vegetarian", "Organic", "Healthy"],
    crowdLevel: "medium",
    openHours: "9:00 AM – 9:30 PM",
  }
];`;

let fileData = fs.readFileSync('src/lib/data.ts', 'utf8');
const startMatch = fileData.indexOf('export const restaurants: Restaurant[] = [');
const endMatch = fileData.indexOf('// === SHOPPING ===');

if (startMatch !== -1 && endMatch !== -1) {
  const finalData = fileData.substring(0, startMatch) + newRestaurants + '\n\n' + fileData.substring(endMatch);
  fs.writeFileSync('src/lib/data.ts', finalData);
  console.log('Successfully updated restaurants array in data.ts');
} else {
  console.log('Could not find markers for replacement.');
}
