const fs = require('fs');

const newShopping = `export const shoppingSpots: ShoppingSpot[] = [
  {
    id: "anjuna-boutique",
    name: "Anjuna Boutique - Kerala Handlooms",
    category: "handmade",
    description: "Authentic Kerala handloom sarees, kasavu fabrics, and traditional crafts.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    priceRange: "₹500 – ₹5,000",
    location: { lat: 8.7370, lng: 76.7150 },
    address: "Temple Road, Varkala",
    tags: ["Handloom", "Saree", "Kasavu", "Traditional"],
  },
  {
    id: "ayurveda-herbal",
    name: "Ayur-Veda Herbal Shop",
    category: "ayurveda",
    description: "Pure Ayurvedic medicines, herbal teas, massage oils, and natural cosmetics.",
    image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800&q=80",
    priceRange: "₹200 – ₹2,000",
    location: { lat: 8.7360, lng: 76.7160 },
    address: "North Cliff, Varkala",
    tags: ["Ayurveda", "Herbal", "Oils", "Wellness"],
  },
  {
    id: "beach-bohemian",
    name: "Beach Bohemian",
    category: "beachwear",
    description: "Colorful beachwear, harem pants, bohemian dresses, and accessories perfect for the cliff vibe.",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80",
    priceRange: "₹300 – ₹2,500",
    location: { lat: 8.7370, lng: 76.7150 },
    address: "Cliff Road, Varkala",
    tags: ["Beachwear", "Bohemian", "Summer Wear", "Trendy"],
  },
  {
    id: "cliff-market",
    name: "Cliff Market – Souvenir Lane",
    category: "souvenirs",
    description: "The bustling main souvenir strip along the clifftop promenade offering everything from magnets to t-shirts.",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80",
    priceRange: "₹100 – ₹2,000",
    location: { lat: 8.7370, lng: 76.7150 },
    address: "North Cliff, Varkala",
    tags: ["Souvenirs", "Magnets", "T-Shirts", "Gifts"],
  },
  {
    id: "dharma-silver",
    name: "Dharma Silver Jewellery",
    category: "jewelry",
    description: "Handcrafted silver jewelry, semi-precious stones, and custom rings made by local artisans.",
    image: "https://images.unsplash.com/photo-1515562141207-7a8efbc88b74?w=800&q=80",
    priceRange: "₹500 – ₹10,000",
    location: { lat: 8.7380, lng: 76.7160 },
    address: "North Cliff, Varkala",
    tags: ["Jewelry", "Silver", "Handcrafted", "Gemstones"],
  },
  {
    id: "ganesh-handicrafts",
    name: "Ganesh Handicrafts & Antiques",
    category: "antiques",
    description: "A treasure trove of antique wooden carvings, brass lamps, and traditional Kerala statues.",
    image: "https://images.unsplash.com/photo-1605333390234-df7675e466cb?w=800&q=80",
    priceRange: "₹1,000 – ₹15,000",
    location: { lat: 8.7350, lng: 76.7160 },
    address: "Temple Road Junction, Varkala",
    tags: ["Antiques", "Brass", "Wood Carvings", "Decor"],
  },
  {
    id: "himalayan-bowls",
    name: "Himalayan Singing Bowls",
    category: "crafts",
    description: "Authentic Tibetan singing bowls, meditation bells, and sound healing instruments.",
    image: "https://images.unsplash.com/photo-1616843413587-9e3a37f7bbd8?w=800&q=80",
    priceRange: "₹800 – ₹5,000",
    location: { lat: 8.7390, lng: 76.7170 },
    address: "North Cliff, Varkala",
    tags: ["Meditation", "Singing Bowls", "Tibetan", "Healing"],
  },
  {
    id: "kairali-ayurveda",
    name: "Kairali Ayurveda Store",
    category: "ayurveda",
    description: "Premium Ayurvedic oils, herbal soaps, and traditional medicine products from established brands.",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80",
    priceRange: "₹150 – ₹3,000",
    location: { lat: 8.7370, lng: 76.7150 },
    address: "South Cliff, Varkala",
    tags: ["Ayurveda", "Oils", "Soaps", "Authentic"],
  },
  {
    id: "kerala-khadi",
    name: "Kerala Khadi Emporium",
    category: "clothing",
    description: "Government-certified store selling pure cotton khadi shirts, kurtas, and sustainable clothing.",
    image: "https://images.unsplash.com/photo-1583391733958-611591eb3600?w=800&q=80",
    priceRange: "₹400 – ₹2,500",
    location: { lat: 8.7320, lng: 76.7180 },
    address: "Railway Station Road, Varkala",
    tags: ["Khadi", "Cotton", "Sustainable", "Clothing"],
  },
  {
    id: "mandala-art",
    name: "Mandala Art Gallery",
    category: "crafts",
    description: "Hand-painted mandalas, local artworks, and canvas prints from regional artists.",
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&q=80",
    priceRange: "₹500 – ₹8,000",
    location: { lat: 8.7365, lng: 76.7155 },
    address: "North Cliff, Varkala",
    tags: ["Art", "Paintings", "Mandala", "Canvas"],
  },
  {
    id: "nomads-wardrobe",
    name: "Nomad's Wardrobe",
    category: "clothing",
    description: "Trendy backpacker clothing, linen pants, and block-printed cotton shirts.",
    image: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800&q=80",
    priceRange: "₹300 – ₹2,000",
    location: { lat: 8.7385, lng: 76.7165 },
    address: "Cliff Pathway, Varkala",
    tags: ["Clothing", "Linen", "Backpacker", "Trendy"],
  },
  {
    id: "ocean-gems",
    name: "Ocean Gems & Crystals",
    category: "jewelry",
    description: "Healing crystals, precious stones, and custom-made macrame jewelry.",
    image: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800&q=80",
    priceRange: "₹200 – ₹4,000",
    location: { lat: 8.7355, lng: 76.7158 },
    address: "North Cliff, Varkala",
    tags: ["Crystals", "Gems", "Macrame", "Healing"],
  },
  {
    id: "pure-linen",
    name: "Pure Linen Varkala",
    category: "clothing",
    description: "High-quality pure linen garments, perfect for the tropical Kerala climate.",
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=800&q=80",
    priceRange: "₹800 – ₹3,500",
    location: { lat: 8.7340, lng: 76.7150 },
    address: "Beach Road, Varkala",
    tags: ["Linen", "Premium", "Clothing", "Summer"],
  },
  {
    id: "spice-village",
    name: "Spice Village Store",
    category: "spices",
    description: "Freshly sourced Kerala spices including cardamom, black pepper, cinnamon, and vanilla.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&q=80",
    priceRange: "₹100 – ₹1,500",
    location: { lat: 8.7368, lng: 76.7162 },
    address: "Temple Junction, Varkala",
    tags: ["Spices", "Kerala", "Fresh", "Gifts"],
  },
  {
    id: "temple-handicrafts",
    name: "Temple Road Handicrafts",
    category: "crafts",
    description: "Locally made coir products, bamboo crafts, and coconut shell souvenirs.",
    image: "https://images.unsplash.com/photo-1531685250784-af587016e6ba?w=800&q=80",
    priceRange: "₹50 – ₹1,000",
    location: { lat: 8.7375, lng: 76.7170 },
    address: "Janardanaswamy Temple Road, Varkala",
    tags: ["Crafts", "Bamboo", "Coir", "Local"],
  },
  {
    id: "tibetan-market",
    name: "Tibetan Market",
    category: "souvenirs",
    description: "Authentic Tibetan artifacts, prayer flags, incense, and clothing brought by Tibetan settlers.",
    image: "https://images.unsplash.com/photo-1525126868853-27ea2aab24ea?w=800&q=80",
    priceRange: "₹50 – ₹3,000",
    location: { lat: 8.7395, lng: 76.7165 },
    address: "North Cliff Edge, Varkala",
    tags: ["Tibetan", "Incense", "Artifacts", "Clothing"],
  },
  {
    id: "varkala-flea",
    name: "Varkala Helipad Flea Market",
    category: "clothing",
    description: "A lively evening market offering the best bargains on clothes, sunglasses, and trinkets.",
    image: "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800&q=80",
    priceRange: "₹100 – ₹1,000",
    location: { lat: 8.7330, lng: 76.7140 },
    address: "Helipad Area, Varkala",
    tags: ["Flea Market", "Bargains", "Evening", "Trinkets"],
  }
];`;

let fileData = fs.readFileSync('src/lib/data.ts', 'utf8');
const startMatch = fileData.indexOf('export const shoppingSpots: ShoppingSpot[] = [');
const endMatch = fileData.indexOf('// === TRANSPORT ROUTES ===');

if (startMatch !== -1 && endMatch !== -1) {
  const finalData = fileData.substring(0, startMatch) + newShopping + '\n\n' + fileData.substring(endMatch);
  fs.writeFileSync('src/lib/data.ts', finalData);
  console.log('Successfully updated shopping array in data.ts');
} else {
  console.log('Could not find markers for replacement.');
}
